name: Tests
run-name: ${{ github.actor }} is testing a stock exchange project
on: [push]
jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm install

    build:
        needs: prepare
        runs-on: ubuntu-latest
        steps:
            - run: npm run build
